Update San

diff --git a/San b/San
--- a/San
+++ b/San
@@ -1,1 +1,118 @@
+#****************************************************************************************
+#
+#  SCRIPT NAME : deduparchival1.sh
+#
+#  PURPOSE : The archival of "Deduped" CIFs to be done after 5 years from the date of deduplication.
+#  IR      :22010080
+#  NAME    : BALAJI KOLLU
+#
+#****************************************************************************************
 
+        export TODAY_DT=`cat $data/file/MFLAGS | cut -c9-16`
+
+
+        rm -f $sysout/PROC_INSERT_1_*
+        rm -f $spool/ARCH_AD_*
+        rm -f $data/file/streams_count
+
+        >$sysout/PROC_INSERT_1_${TODAY_DT}.log
+
+        #############DATE#############################
+
+                var_table=`sqlplus -s / <<EOF
+                                set veri off
+                                select EXTRACT(YEAR FROM CURRENT_DATE) AS year FROM DUAL;
+                                exit;
+                                EOF`
+                export var1=`echo "$var_table" |awk  'NR==4''{print $1}' `
+
+                                if [ ! -s $card/DEDUPED_ARCHIVAL_PERIOD.card ];
+                                then
+                                                        if [ $AUTOSYS_MODE = Y ]
+                                                        then
+                                                                echo "ATTENTION ! CANNOT FIND CARD FILE ..."
+                                                                echo "ABORTING PROCESSING.... "
+                                                                exit 1
+                                                        else
+                                                                echo "ATTENTION ! CANNOT FIND CARD FILE ..."
+                                                                exit 1
+                                                        fi
+                                fi
+
+
+
+                while  read -r line
+                do
+                                export yyyy=$(expr $var1 - $line)
+
+                done < "$card/DEDUPED_ARCHIVAL_PERIOD.card"
+
+                current_date=$(date +"$yyyy%m%d")
+                echo "$current_date"
+
+
+                        var_table=`sqlplus -s / <<EOF
+                                        set veri off
+                                        select to_char(to_date($current_date,'YYYYMMDD'),'J')-2415020 "BINARY DATE" f
+rom dual;
+                                        exit;
+                                        EOF`
+                                                cd $spool
+
+                                if [ $no_of_output_files -eq '1' ]; then
+
+                                        if [ $count  -ge 10000 ]
+                                           then
+
+                                                split -l $(expr $count / 30) $spool/DEDUP_AD_${TODAY_DT}_OUTPUT.txt |
+awk 'NF'
+                                                        j=000
+                                                        typeset -Z3 j
+                                                        for i in `ls $spool/x?? `
+                                                         do
+                                                          j=`expr $j + 1`
+                                                          mv -f $i $spool/ARCH_AD_$j > $data/file/streams_count
+                                                        done
+                                        else
+                                                split -l $count1  $spool/DEDUP_AD_${TODAY_DT}_OUTPUT.txt |awk 'NF'
+                                                 j=000
+                                                 typeset -Z3 j
+                                                 for i in `ls $spool/x?? `
+                                                  do
+                                                  j=`expr $j + 1`
+                                                  mv -f $i $spool/ARCH_AD_$j > $data/file/streams_count
+                                                done
+                                        fi
+
+                                fi
+
+        ll -lrt $spool/ARCH_AD_??? | wc -l > $data/file/streams_count
+
+
+
+        ################################################
+
+                        echo "INSERTING OF DATA INTO TEMPORARY TABLE " >>$sysout/PROC_BKP_1_${TODAY_DT}.log
+                        a=001
+                        b=`cat $data/file/streams_count`
+                                typeset -Z3 b
+                        while [ $a -le $b ]
+                        do
+                                        $sh/deduparchivai_2280.sh ${a} -s 2>&1 &
+                                        a=`expr ${a} + 1`
+                                        typeset -Z3 a
+                        done
+######All Streams have been submitted and monitor them
+   while :
+   do
+
+   stream_running=`ps -ef | grep deduparchivai_2280.sh | grep -v grep | wc -l`
+
+   if [ $stream_running -eq 0 ];then
+      echo "RUNNING " $stream_running " STREAM(S) OF .....deduparchivai_2280.sh"
+      sleep 30
+   else
+      echo "COMPLETED deduparchivai_2280.sh.... SUMMARY IS AS FOLLOWS"
+      break;
+   fi
+   done
